# Database
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql145758-zedrax.jelasticlw.com.br:3306/zedrax?useTimezone=true&serverTimezone=UTC&useSSL=false
    user: root
    password: IEFmfs37535
#    url: jdbc:mysql://189.1.162.28:3306/zedraxco_zedrax?useTimezone=true&serverTimezone=UTC&useSSL=false
#    user: zedraxco_zedrax
#    password: "#zedrax#!@#Z#@!"
#    url: jdbc:mysql://localhost:3306/zedrax?useTimezone=true&serverTimezone=UTC&useSSL=false
#    user: root
#    password: root
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL57Dialect
  generate-ddl: true
  show-sql: true
  jdbc:
    fetch-size: 100
  hbm2ddl:
    auto: update
  entity-scan: br.com.zedrax.services.model
  repositories-scan: br.com.zedrax.services.repository
  persistence-unit: default

# Data for Loaders

# Piece Types
piece-type:
  king: KING
  queen: QUEEN
  rook: ROOK
  bishop: BISHOP
  knight: KNIGHT
  warrior: WARRIOR
  tank: TANK
  archer: ARCHER
  ninja: NINJA

# Piece Type Classes
piece-class:
  pawn: PAWN
  elite: ELITE

# Settings
settings:
  group:
    audio: AUDIO
    display: DISPLAY
  attribute:
    audio:
      music:
        description: MUSIC
        default-value: 10
      sfx:
        description: SFX
        default-value: 10
      speech:
        description: SPEECH
        default-value: 10
    display:
      resolution:
        description: RESOLUTION
        default-value: 10

# Action
action:
  type:
    move: MOVE
    attack: ATTACK

# Game Settings
game:
  board:
    width: 10
    height: 10
  turn:
    initial-mana: 10