# Database

# SQLite
#spring:
#  datasource:
#    driver: org.sqlite.JDBC
#    url: jdbc:sqlite:D:\OneDrive\Documents\Personal\Studies\Faculdade\Ciência da Computação\tcc\database\zedrax.db
#    user: 
#    password: 

# MySQL
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zedrax?useTimezone=true&serverTimezone=UTC&useSSL=false
    user: root
    password: root
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 5000
# Hibernate
hibernate:
#  dialect: br.com.zedrax.zedraxservices.dialect.SQLiteDialect
  dialect: org.hibernate.dialect.MySQL57Dialect
  generate_ddl: true
  show_sql: true
  jdbc:
    fetch_size: 100
  hbm2ddl:
    auto: update
  entity_scan: br.com.zedrax.services.model
  repositories_scan: br.com.zedrax.services.repository
  persistence_unit: default

# Data for Loaders
# Account Status
account_status:
  waiting_confirmation: WAITING_CONFIRMATION
  active: ACTIVE
  inactive: INACTIVE
  blocked: BLOCKED
  deleted: DELETED

# Piece Types
piece_type:
  king: KING
  queen: QUEEN
  rook: ROOK
  bishop: BISHOP
  knight: KNIGHT
  warrior: WARRIOR
  tank: TANK
  archer: ARCHER
  ninja: NINJA

# Piece Type Classes
piece_type_class:
  pawn: PAWN
  elite: ELITE

# Settings
settings:
  group:
    audio: AUDIO
    display: DISPLAY
  attribute:
    audio:
      music:
        description: MUSIC
        default_value: 10
      sfx:
        description: SFX
        default_value: 10
      speech:
        description: SPEECH
        default_value: 10
    display:
      resolution:
        description: RESOLUTION
        default_value: 10