# Database
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zedrax?useTimezone=true&serverTimezone=UTC&useSSL=false
    user: root
    password: root

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL57Dialect
  generate_ddl: true
  show_sql: true
  jdbc:
    fetch_size: 100
  hbm2ddl:
    auto: update
  entity_scan: br.com.zedrax.services.model
  repositories_scan: br.com.zedrax.services.repository
  persistence_unit: default

# Data for Loaders

# Piece Types
piece_type:
  king: KING
  queen: QUEEN
  rook: ROOK
  bishop: BISHOP
  knight: KNIGHT
  warrior: WARRIOR
  tank: TANK
  archer: ARCHER
  ninja: NINJA

# Piece Type Classes
piece_class:
  pawn: PAWN
  elite: ELITE

# Settings
settings:
  group:
    audio: AUDIO
    display: DISPLAY
  attribute:
    audio:
      music:
        description: MUSIC
        default_value: 10
      sfx:
        description: SFX
        default_value: 10
      speech:
        description: SPEECH
        default_value: 10
    display:
      resolution:
        description: RESOLUTION
        default_value: 10

# Action
action:
  type:
    move: MOVE
    attack: ATTACK